databases: # this section provides some additional database configuration
  - name: notes
    plan: free
    databaseName: notes
    user: notes

services:
  - type: web
    name: notes # the name of this service, eg hello-world
    env: ruby # this app is written in ruby
    plan: free # make sure to set this to free or you'll get billed $$$
    buildCommand: "./bin/render-build.sh" # # we already created these two files for you
    startCommand: "./bin/render-start.sh"
    envVars: # this section sets some ENV variables needed by Render for deployment
      - key: DATABASE_URL
        fromDatabase:
          name: notes
          property: connectionString
      - key: SECRET_KEY_BASE
        generateValue: true
